# fly.toml app configuration file generated for spanish on 2023-09-24T14:52:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spanish"
primary_region = "lhr"

[processes]
  api = "./app/api/conjugation-api"
  ui = "node ./ui/build/"

[[services]]
  processes = ["api"]
  protocol = "tcp"
  internal_port = 8080

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["ui"]
